SystemUI: grant FORCE_STOP_PACKAGES permission
java.lang.SecurityException: Permission Denial: forceStopPackage() from pid=2979, uid=10034 requires android.permission.FORCE_STOP_PACKAGES

Change-Id: Iced4faa0694c5ba19f5b14c8c67326fea2178b3d